# Generated by Django 3.2.5 on 2021-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('view_count', models.IntegerField()),
                ('answer_count', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
